obj-$(CONFIG_HORAE_THERMAL_SHELL) += thermal/
obj-$(CONFIG_OPLUS_DEVICE_INFO) += device_info/
obj-y += boot/
obj-y += dfr/
obj-y += mdmrst/
obj-y += dft/
obj-y += drivers/
obj-$(CONFIG_OPLUS_SENSOR_FB_QC) += oplus_sensor_feedback/
