# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#ifdef OPLUS_FEATURE_ZRAM_OPT
#obj-$(CONFIG_OPLUS_FEATURE_ZRAM_OPT) 	+= zram_opt/
#endif /* CONFIG_OPLUS_FEATURE_ZRAM_OPT */


#ifdef OPLUS_FEATURE_HYBRIDSWAP_ZRAM
obj-$(CONFIG_HYBRIDSWAP_ZRAM) += hybridswap_zram/
#endif

##obj-y += mm_osvelte/
